const tr = {
  title: 'Destek Talepleri',
  subtitle: 'Taleplerinizi görüntüleyin veya yeni bir talep oluşturun.',
  newTicket: 'Yeni Talep',
  empty: 'Henüz destek talebiniz yok.',
  back: 'Panele dön',
  backToList: 'Taleplere dön',
  createTitle: 'Destek Talebi Oluştur',
  createSubtitle: 'Yardıma ihtiyaç duyduğunuz konuyu anlatın, en kısa sürede size dönelim.',
  department: 'Departman',
  departmentPlaceholder: 'Bir departman seçin',
  priority: 'Öncelik',
  service: 'İlgili Hizmet',
  optional: '(isteğe bağlı)',
  serviceNone: 'Belirli bir hizmetle ilgili değil',
  serviceHint: 'Bir hizmet bağlamak talebinizi daha hızlı çözmemize yardımcı olur.',
  project: 'İlgili Site',
  projectNone: 'Belirli bir siteyle ilgili değil',
  subject: 'Konu',
  subjectPlaceholder: 'Sorununuzu kısaca açıklayın',
  message: 'Mesaj',
  messagePlaceholder:
    'Mümkün olduğunca ayrıntı paylaşın: hata mesajları, etkilenen alan adı veya hizmet ve daha önce denediğiniz adımlar',
  attachments: 'Ekler',
  browse: 'Gözat',
  dropHint: 'veya dosyaları buraya bırakın',
  attachHint: 'PNG, JPG, WEBP, PDF veya TXT · en fazla 5 dosya · dosya başına 5 MB',
  remove: 'Kaldır',
  cancel: 'İptal',
  submit: 'Talebi Gönder',
  sending: 'Gönderiliyor…',
  beforeTitle: 'Talep Oluşturmadan Önce',
  beforeBody: 'Birçok sorunun yanıtı sıkça sorulan sorularda var. Hızlı bir arama sorununuzu hemen çözebilir.',
  beforeCta: 'Sık Sorulan Sorulara Git',
  nextTitle: 'Bundan Sonra Ne Olacak',
  nextBody1: 'Talepler destek sırası ve ekip müsaitliğine göre ele alınır ve en kısa sürede yanıtlanır.',
  nextBody2:
    'Ekibimiz yanıt verdiğinde size e-posta göndeririz; konuşmayı istediğiniz zaman destek taleplerinden takip edebilirsiniz.',
  created: 'Talebiniz alındı',
  yourReply: 'Yanıtınız',
  replyPlaceholder: 'Mesajınızı yazın…',
  send: 'Gönder',
  you: 'Siz',
  team: 'Destek Ekibi',
  ticketNo: 'Talep no',
  createdAt: 'Oluşturuldu',
  updatedAt: 'Güncellendi',
  status: {
    open: 'Açık',
    in_progress: 'İşlemde',
    waiting_user: 'Yanıtınız bekleniyor',
    answered: 'Yanıtlandı',
    resolved: 'Çözüldü',
  },
  priorities: { low: 'Düşük', normal: 'Orta', high: 'Yüksek' },
  departments: {
    technical: 'Teknik Destek',
    billing: 'Faturalama',
    domain: 'Alan Adı',
    website: 'Web Sitesi',
    ai: 'Yapay Zeka',
    account: 'Hesap',
    other: 'Diğer',
  },
  services: {
    website: 'Web Sitesi',
    ecommerce: 'E-ticaret',
    ai_content: 'AI İçerik',
    visual_logo: 'Görsel ve Logo',
    domain: 'Alan Adı',
    hosting: 'Barındırma',
    billing: 'Faturalama',
    other: 'Diğer',
  },
  errors: {
    unauthenticated: 'Oturumunuz sona ermiş. Lütfen tekrar giriş yapın.',
    invalid_department: 'Lütfen bir departman seçin.',
    invalid_priority: 'Geçersiz öncelik.',
    invalid_service: 'Geçersiz hizmet.',
    invalid_project: 'Seçilen site bulunamadı.',
    invalid_subject: 'Konu zorunludur (en fazla 150 karakter).',
    invalid_message: 'Mesaj zorunludur (en fazla 5000 karakter).',
    too_many_files: 'En fazla 5 dosya ekleyebilirsiniz.',
    file_too_large: 'Her dosya en fazla 5 MB olabilir.',
    file_type_not_allowed: 'Yalnızca PNG, JPG, WEBP, PDF veya TXT yüklenebilir.',
    upload_failed: 'Dosya yüklenemedi. Lütfen tekrar deneyin.',
    ticket_not_found: 'Talep bulunamadı.',
    send_failed: 'Mesaj gönderilemedi.',
    create_failed: 'Talep oluşturulamadı. Lütfen tekrar deneyin.',
    generic: 'Bir şeyler ters gitti. Lütfen tekrar deneyin.',
  } as Record<string, string>,
}

export type SupportCopy = typeof tr

const en: SupportCopy = {
  title: 'Support Tickets',
  subtitle: 'View your tickets or open a new one.',
  newTicket: 'New Ticket',
  empty: 'You have no support tickets yet.',
  back: 'Back to dashboard',
  backToList: 'Back to tickets',
  createTitle: 'Create Support Ticket',
  createSubtitle: 'Tell us what you need help with and we will get back to you shortly.',
  department: 'Department',
  departmentPlaceholder: 'Select a department',
  priority: 'Priority',
  service: 'Related Service',
  optional: '(optional)',
  serviceNone: 'Not related to a specific service',
  serviceHint: 'Linking a service helps us resolve your ticket faster.',
  project: 'Related Site',
  projectNone: 'Not related to a specific site',
  subject: 'Subject',
  subjectPlaceholder: 'Briefly describe your issue',
  message: 'Message',
  messagePlaceholder:
    'Share as much detail as you can: error messages, the affected domain or service, and steps you already tried',
  attachments: 'Attachments',
  browse: 'Browse',
  dropHint: 'or drop files here',
  attachHint: 'PNG, JPG, WEBP, PDF or TXT · up to 5 files · 5 MB each',
  remove: 'Remove',
  cancel: 'Cancel',
  submit: 'Submit Ticket',
  sending: 'Sending…',
  beforeTitle: 'Before You Submit',
  beforeBody: 'Many answers are in our FAQ. A quick search may solve your issue right away.',
  beforeCta: 'Go to FAQ',
  nextTitle: 'What Happens Next',
  nextBody1: 'Tickets are handled by queue order and team availability, and answered as soon as possible.',
  nextBody2: 'We email you when our team replies; you can follow the conversation from your support tickets anytime.',
  created: 'Ticket received',
  yourReply: 'Your reply',
  replyPlaceholder: 'Write your message…',
  send: 'Send',
  you: 'You',
  team: 'Support Team',
  ticketNo: 'Ticket no',
  createdAt: 'Created',
  updatedAt: 'Updated',
  status: {
    open: 'Open',
    in_progress: 'In progress',
    waiting_user: 'Awaiting your reply',
    answered: 'Answered',
    resolved: 'Resolved',
  },
  priorities: { low: 'Low', normal: 'Medium', high: 'High' },
  departments: {
    technical: 'Technical Support',
    billing: 'Billing',
    domain: 'Domain',
    website: 'Website',
    ai: 'AI',
    account: 'Account',
    other: 'Other',
  },
  services: {
    website: 'Website',
    ecommerce: 'E-commerce',
    ai_content: 'AI Content',
    visual_logo: 'Visuals and Logo',
    domain: 'Domain',
    hosting: 'Hosting',
    billing: 'Billing',
    other: 'Other',
  },
  errors: {
    unauthenticated: 'Your session expired. Please sign in again.',
    invalid_department: 'Please select a department.',
    invalid_priority: 'Invalid priority.',
    invalid_service: 'Invalid service.',
    invalid_project: 'The selected site was not found.',
    invalid_subject: 'Subject is required (150 characters max).',
    invalid_message: 'Message is required (5000 characters max).',
    too_many_files: 'You can attach up to 5 files.',
    file_too_large: 'Each file can be up to 5 MB.',
    file_type_not_allowed: 'Only PNG, JPG, WEBP, PDF or TXT files are allowed.',
    upload_failed: 'File upload failed. Please try again.',
    ticket_not_found: 'Ticket not found.',
    send_failed: 'Message could not be sent.',
    create_failed: 'Could not create the ticket. Please try again.',
    generic: 'Something went wrong. Please try again.',
  },
}

export function getSupportCopy(lang: string): SupportCopy {
  return lang === 'tr' ? tr : en
}
