import { VERCEL_DEFAULT_A, VERCEL_DEFAULT_CNAME, type VercelAddResult, type VercelClient, type VercelVerificationChallenge } from './vercel'
import type { DnsRecord, DnsStage, DomainConnection, SslStage, VercelStage } from './types'

/**
 * Domain connection pipeline: ownership TXT -> Vercel attach -> DNS -> SSL.
 * Every external effect (DNS-over-HTTPS, HTTPS probe, Vercel API) is injected
 * so the state machine is unit-testable without a network.
 */

export const OWNERSHIP_HOST = '_gloval'
export const OWNERSHIP_PREFIX = 'gloval-site-verification='

export function newVerificationToken(): string {
  const bytes = new Uint8Array(16)
  globalThis.crypto.getRandomValues(bytes)
  return Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('')
}

/** Fully-qualified name a record lives at, for DNS lookups. */
export function recordFqdn(domain: string, host: string): string {
  return host === '@' ? domain : `${host}.${domain}`
}

/** Targets used ONLY to judge whether DNS already points at Vercel. Never rendered as records. */
export type WebsiteTargets = { a: string[]; cname: string }

export const DEFAULT_TARGETS: WebsiteTargets = { a: [VERCEL_DEFAULT_A], cname: VERCEL_DEFAULT_CNAME }

/** Targets Vercel's config API actually returned for this domain; the only values shown as website records. */
export type DisplayTargets = { a?: string; cname?: string }

const CHALLENGE_TYPES: ReadonlySet<DnsRecord['type']> = new Set(['TXT', 'A', 'AAAA', 'CNAME'])

/** Host a Vercel challenge must be published at, relative to the customer's zone. */
export function challengeHost(challengeDomain: string, domain: string): string {
  const name = challengeDomain.trim().toLowerCase().replace(/\.$/, '')
  if (name === domain) return '@'
  if (name.endsWith(`.${domain}`)) return name.slice(0, -(domain.length + 1))
  // Outside this domain's own labels (e.g. `_vercel.<apex>` requested for a subdomain):
  // show the full name exactly as Vercel reported it instead of guessing a host.
  return name
}

/**
 * Builds the customer-facing record set.
 *  - The ownership TXT is generated by us (`source: 'gloval'`).
 *  - Verification challenges and website targets are copied from Vercel API
 *    responses (`source: 'vercel'`). When Vercel has not supplied website
 *    targets, NO website record is emitted: nothing is invented. Website records
 *    Vercel reported on an earlier check are kept so a transient API failure
 *    does not make them disappear.
 *  - Email records are carried over untouched from `existing`.
 */
export function buildDnsRecords(input: {
  domain: string
  token: string
  existing: DnsRecord[]
  targets?: DisplayTargets
  ownershipVerified: boolean
  vercelChallenges?: VercelVerificationChallenge[]
  websiteConfigured?: boolean
}): DnsRecord[] {
  const email = input.existing.filter((r) => r.purpose === 'email')

  const records: DnsRecord[] = [
    {
      type: 'TXT',
      host: OWNERSHIP_HOST,
      value: `${OWNERSHIP_PREFIX}${input.token}`,
      purpose: 'verification',
      verified: input.ownershipVerified,
      source: 'gloval',
      placeholder: false,
    },
  ]

  const seen = new Set<string>()
  for (const challenge of input.vercelChallenges ?? []) {
    const type = challenge.type.toUpperCase() as DnsRecord['type']
    if (!CHALLENGE_TYPES.has(type)) continue
    const host = challengeHost(challenge.domain, input.domain)
    const key = `${type}|${host}|${challenge.value}`
    if (seen.has(key)) continue
    seen.add(key)
    records.push({ type, host, value: challenge.value, purpose: 'verification', verified: false, source: 'vercel', placeholder: false })
  }

  const configured = input.websiteConfigured === true
  const targets = input.targets
  if (targets && (targets.a || targets.cname)) {
    if (targets.a) {
      records.push({ type: 'A', host: '@', value: targets.a, purpose: 'website', verified: configured, source: 'vercel', placeholder: false })
    }
    if (targets.cname) {
      records.push({ type: 'CNAME', host: 'www', value: targets.cname, purpose: 'website', verified: configured, source: 'vercel', placeholder: false })
    }
  } else {
    for (const previous of input.existing) {
      if (previous.purpose === 'website' && previous.source === 'vercel') records.push({ ...previous, verified: configured })
    }
  }

  return [...records, ...email]
}

/* ------------------------------ DNS resolver ------------------------------ */

export interface DnsResolver {
  txt(name: string): Promise<string[]>
  a(name: string): Promise<string[]>
  cname(name: string): Promise<string[]>
  /** MX exchange hostnames (lowercase, no trailing dot). Optional so existing test resolvers stay valid. */
  mx?(name: string): Promise<string[]>
}

async function doh(name: string, type: string): Promise<Array<{ type?: number; data?: string }>> {
  const response = await fetch(
    `https://cloudflare-dns.com/dns-query?name=${encodeURIComponent(name)}&type=${type}`,
    { headers: { accept: 'application/dns-json' }, cache: 'no-store', signal: AbortSignal.timeout(8_000) },
  )
  if (!response.ok) throw new Error(`DNS-over-HTTPS returned ${response.status}`)
  const payload = (await response.json()) as { Answer?: Array<{ type?: number; data?: string }> }
  return payload.Answer ?? []
}

export const dohResolver: DnsResolver = {
  async txt(name) {
    const answers = await doh(name, 'TXT')
    return answers
      .filter((a) => a.type === 16 && typeof a.data === 'string')
      .map((a) => a.data!.replace(/^"|"$/g, '').replace(/"\s+"/g, ''))
  },
  async a(name) {
    const answers = await doh(name, 'A')
    return answers.filter((a) => a.type === 1 && typeof a.data === 'string').map((a) => a.data!)
  },
  async cname(name) {
    const answers = await doh(name, 'CNAME')
    return answers.filter((a) => a.type === 5 && typeof a.data === 'string').map((a) => a.data!.replace(/\.$/, ''))
  },
  async mx(name) {
    const answers = await doh(name, 'MX')
    return answers
      .filter((a) => a.type === 15 && typeof a.data === 'string')
      .map((a) => a.data!.trim().split(/\s+/).pop()!.replace(/\.$/, '').toLowerCase())
  },
}

/** Any HTTP response over TLS counts; a TLS/handshake failure does not. */
export async function probeHttps(host: string): Promise<boolean> {
  try {
    await fetch(`https://${host}/`, {
      method: 'HEAD',
      redirect: 'manual',
      cache: 'no-store',
      signal: AbortSignal.timeout(8_000),
    })
    return true
  } catch {
    return false
  }
}

export type OwnershipResult = 'verified' | 'missing' | 'unavailable'

/**
 * Checks the ownership TXT record. `unavailable` means the DNS lookup itself
 * failed (resolver outage/timeout): that is not evidence the record is absent,
 * so callers must not mark the domain failed because of it.
 */
export async function checkOwnership(
  domain: string,
  record: Pick<DnsRecord, 'host' | 'value'>,
  resolver: DnsResolver,
): Promise<OwnershipResult> {
  try {
    const values = await resolver.txt(recordFqdn(domain, record.host))
    return values.includes(record.value) ? 'verified' : 'missing'
  } catch {
    return 'unavailable'
  }
}

/* ----------------------------- stage computation ----------------------------- */

export type ConnectionDeps = {
  vercel: VercelClient
  resolver: DnsResolver
  probe: (host: string) => Promise<boolean>
  now: () => Date
}

export type ConnectionInput = {
  domain: string
  token: string
  dns: DnsRecord[]
  legacy: boolean
  /**
   * False while the ownership TXT has not been proven. The Vercel attach and
   * record fetch still run (the project is chosen first), but the TXT record is
   * then shown as not yet verified. Defaults to true.
   */
  ownershipVerified?: boolean
}

export type WwwOutcome = 'skipped' | 'added' | 'present' | 'updated' | 'failed'

export type ConnectionResult = {
  connection: DomainConnection
  dns: DnsRecord[]
  vercelChallenges: VercelVerificationChallenge[]
  /**
   * At least one check could not produce a trustworthy answer (timeout, 5xx,
   * rejected credentials, DoH outage, failed probe). A previously ready domain
   * must not be demoted by this alone.
   */
  inconclusive: boolean
  inconclusiveReason: string | null
  www: WwwOutcome
}

/** Consecutive inconclusive checks after which a ready domain is no longer trusted. */
export const MAX_INCONCLUSIVE_CHECKS = 3

const INCONCLUSIVE_RE = /^inconclusive:[^:]*:(\d+)$/

function sanitizeReason(reason: string): string {
  return reason.replace(/[^a-zA-Z0-9_.-]/g, '_').slice(0, 60)
}

function isReady(c: DomainConnection): boolean {
  return !c.legacy && c.dns === 'configured' && c.vercel === 'connected' && c.ssl === 'ready'
}

/**
 * Applies hysteresis: a ready domain survives up to MAX_INCONCLUSIVE_CHECKS - 1
 * consecutive inconclusive checks (only `lastCheckedAt`/`lastError` change).
 * Definitive results always replace the previous state immediately.
 */
export function mergeWithPrevious(previous: DomainConnection, result: ConnectionResult): DomainConnection {
  const next = result.connection
  if (!result.inconclusive || !isReady(previous)) return next

  const previousStreak = Number(INCONCLUSIVE_RE.exec(previous.lastError ?? '')?.[1] ?? 0)
  const streak = previousStreak + 1
  const lastError = `inconclusive:${result.inconclusiveReason ?? 'unknown'}:${streak}`
  if (streak >= MAX_INCONCLUSIVE_CHECKS) return { ...next, lastError }
  return { ...previous, lastCheckedAt: next.lastCheckedAt, lastError }
}

type AttachOutcome = {
  stage: VercelStage
  challenges: VercelVerificationChallenge[]
  error?: Extract<VercelAddResult, { ok: false }>
}

async function guard(call: () => Promise<VercelAddResult>): Promise<VercelAddResult> {
  try {
    return await call()
  } catch (error) {
    return {
      ok: false,
      code: 'network_error',
      message: error instanceof Error ? error.message : 'unknown',
      status: 0,
      inconclusive: true,
    }
  }
}

/**
 * Attach + verify. A 400 from verify while challenges are outstanding is the
 * normal "TXT not published yet" answer, so the challenges from `add` are kept
 * and surfaced instead of being replaced by an opaque error.
 */
async function attachToVercel(domain: string, vercel: VercelClient): Promise<AttachOutcome> {
  const added = await guard(() => vercel.addDomain(domain))
  if (!added.ok) return { stage: 'error', challenges: [], error: added }
  if (added.verified) return { stage: 'connected', challenges: [] }

  const verified = await guard(() => vercel.verifyDomain(domain))
  if (verified.ok) {
    if (verified.verified) return { stage: 'connected', challenges: [] }
    return {
      stage: 'needs_verification',
      challenges: verified.verification.length > 0 ? verified.verification : added.verification,
    }
  }
  if (verified.status === 400 && added.verification.length > 0) {
    return { stage: 'needs_verification', challenges: added.verification }
  }
  return { stage: 'error', challenges: added.verification, error: verified }
}

/**
 * www -> apex redirect. Creates it, or rewrites an existing www entry whose
 * redirect is missing/different. Never throws; failure is reported, not fatal.
 */
export async function ensureWwwRedirect(
  domain: string,
  vercel: VercelClient,
): Promise<{ outcome: WwwOutcome; error?: string }> {
  const www = `www.${domain}`
  const added = await guard(() => vercel.addDomain(www, { redirectTo: domain }))
  if (!added.ok) return { outcome: 'failed', error: added.code }

  if (added.redirect === domain || (added.redirect === undefined && !added.existing)) {
    return { outcome: added.existing ? 'present' : 'added' }
  }
  const updated = await guard(() => vercel.setRedirect(www, domain))
  return updated.ok ? { outcome: 'updated' } : { outcome: 'failed', error: updated.code }
}

/**
 * Runs the post-ownership stages for a domain whose TXT is already verified.
 * Never throws: failures are captured in `connection.lastError` and the result
 * is flagged `inconclusive` when it cannot be trusted either way.
 */
export async function runConnectionCheck(input: ConnectionInput, deps: ConnectionDeps): Promise<ConnectionResult> {
  try {
    return await runChecks(input, deps)
  } catch (error) {
    const reason = sanitizeReason(error instanceof Error ? `internal_${error.name}` : 'internal')
    return {
      connection: {
        dns: 'pending',
        vercel: 'error',
        ssl: 'pending',
        lastCheckedAt: deps.now().toISOString(),
        lastError: `inconclusive:${reason}:1`,
        legacy: input.legacy,
      },
      dns: input.dns,
      vercelChallenges: [],
      inconclusive: true,
      inconclusiveReason: reason,
      www: 'skipped',
    }
  }
}

async function runChecks(input: ConnectionInput, deps: ConnectionDeps): Promise<ConnectionResult> {
  const { domain, token, legacy } = input
  const checkedAt = deps.now().toISOString()
  let targets: WebsiteTargets = DEFAULT_TARGETS
  let displayTargets: DisplayTargets | undefined
  let challenges: VercelVerificationChallenge[] = []
  let lastError: string | null = null
  let inconclusiveReason: string | null = null
  let www: WwwOutcome = 'skipped'
  const markInconclusive = (reason: string) => {
    inconclusiveReason ??= sanitizeReason(reason)
  }

  // Without a Vercel integration a legacy (already-serving) row is left alone:
  // we must not demote a live site just because the API token is not set here.
  if (!deps.vercel.configured && legacy) {
    return {
      connection: { dns: 'pending', vercel: 'not_configured', ssl: 'pending', lastCheckedAt: checkedAt, lastError: null, legacy: true },
      dns: input.dns,
      vercelChallenges: [],
      inconclusive: false,
      inconclusiveReason: null,
      www,
    }
  }

  let vercel: VercelStage = 'not_configured'
  if (deps.vercel.configured) {
    const attach = await attachToVercel(domain, deps.vercel)
    vercel = attach.stage
    challenges = attach.challenges
    if (attach.error) {
      lastError = `vercel:${attach.error.code}`
      if (attach.error.inconclusive) markInconclusive(`vercel_${attach.error.code}`)
    } else if (vercel === 'needs_verification' && challenges.length === 0) {
      lastError = 'vercel:challenge_missing'
    }

    if (vercel === 'connected') {
      const wwwResult = await ensureWwwRedirect(domain, deps.vercel)
      www = wwwResult.outcome
      if (wwwResult.outcome === 'failed') lastError ??= `www:${wwwResult.error ?? 'failed'}`
    }
  }

  // DNS: Vercel's own judgement wins once the domain is attached to the project
  // (including while it still waits for an extra ownership TXT), and its config
  // response is the only source of the website targets we display. Otherwise
  // fall back to resolving the records ourselves.
  let dns: DnsStage = 'pending'
  if (vercel === 'connected' || vercel === 'needs_verification') {
    let config: Awaited<ReturnType<VercelClient['getConfig']>> = null
    try {
      config = await deps.vercel.getConfig(domain)
    } catch {
      config = null
    }
    if (config) {
      if (config.recommendedIPv4[0] || config.recommendedCNAME[0]) {
        displayTargets = { a: config.recommendedIPv4[0], cname: config.recommendedCNAME[0] }
        targets = {
          a: config.recommendedIPv4.length > 0 ? config.recommendedIPv4 : DEFAULT_TARGETS.a,
          cname: config.recommendedCNAME[0] ?? DEFAULT_TARGETS.cname,
        }
      }
      if (!config.misconfigured) {
        dns = 'configured'
      } else {
        // Vercel only says "not right yet". No records at all is still "waiting";
        // records that point elsewhere are "incorrect".
        const seen = await resolveDnsStage(domain, targets, deps.resolver)
        dns = seen === 'pending' ? 'pending' : 'misconfigured'
      }
    } else {
      markInconclusive('config_unavailable')
    }
  } else {
    const resolved = await resolveDnsStage(domain, targets, deps.resolver)
    if (resolved === null) markInconclusive('dns_lookup')
    else dns = resolved
  }

  let ssl: SslStage = 'pending'
  if (vercel === 'connected' && dns === 'configured') {
    let reachable = false
    try {
      reachable = await deps.probe(domain)
    } catch {
      reachable = false
    }
    if (reachable) ssl = 'ready'
    else markInconclusive('probe_failed')
  }

  if (inconclusiveReason && lastError === null) lastError = `inconclusive:${inconclusiveReason}:1`

  const records = buildDnsRecords({
    domain,
    token,
    existing: input.dns,
    targets: displayTargets,
    ownershipVerified: input.ownershipVerified ?? true,
    vercelChallenges: challenges,
    websiteConfigured: dns === 'configured',
  })

  return {
    connection: { dns, vercel, ssl, lastCheckedAt: checkedAt, lastError, legacy: false },
    dns: records,
    vercelChallenges: challenges,
    inconclusive: inconclusiveReason !== null,
    inconclusiveReason,
    www,
  }
}

/** `null` means the lookup itself failed (unknown), not that records are absent. */
async function resolveDnsStage(domain: string, targets: WebsiteTargets, resolver: DnsResolver): Promise<DnsStage | null> {
  try {
    const apex = await resolver.a(domain)
    if (apex.length === 0) {
      const cname = await resolver.cname(domain)
      if (cname.some((c) => c === targets.cname)) return 'configured'
      return 'pending'
    }
    return apex.some((ip) => targets.a.includes(ip)) ? 'configured' : 'misconfigured'
  } catch {
    return null
  }
}
