'use client'

import { useState } from 'react'
import { ChevronDown, Clipboard, Check } from 'lucide-react'
import { getMailSetupCopy } from './setup-copy'
export function MailSetupGuide({ mailboxes, webmailBase, mailServerHost, lang }: { mailboxes: { address: string }[]; webmailBase: string | null; mailServerHost: string; lang: string }) {
  const [open, setOpen] = useState(false); const [tab, setTab] = useState<'android' | 'iphone' | 'outlook'>('android'); const [copied, setCopied] = useState<string | null>(null)
  const c = getMailSetupCopy(lang); const address = mailboxes[0]?.address ?? ''; const host = mailServerHost; const webmail = webmailBase ?? ''
  const copy = async (key: string, value: string) => { await navigator.clipboard.writeText(value); setCopied(key); window.setTimeout(() => setCopied(null), 1500) }
  const rows = [[c.username, address], [c.incoming, `${host} · 993 · SSL/TLS`], [c.outgoing, `${host} · 465 · SSL/TLS`], [c.alternative, `${host} · 587 · STARTTLS`], [c.webmail, webmail]]
  const steps = tab === 'android' ? c.androidSteps : tab === 'iphone' ? c.iphoneSteps : c.outlookSteps
  return <section className="mt-10 rounded-2xl border border-border bg-card/70 p-5 sm:p-6"><button type="button" className="flex w-full items-center justify-between gap-3 text-left" aria-expanded={open} aria-controls="mail-setup-guide" onClick={() => setOpen(!open)}><span><span className="block font-display text-lg font-semibold">{c.title}</span><span className="mt-1 block text-sm text-muted-foreground">{c.intro}</span></span><ChevronDown className={`size-5 shrink-0 transition-transform ${open ? 'rotate-180' : ''}`} /></button>{open && <div id="mail-setup-guide" className="mt-6 space-y-6"><div className="grid gap-2">{rows.map(([label, value]) => <div key={label} className="flex flex-col gap-2 rounded-lg border border-border bg-muted/30 p-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="text-xs text-muted-foreground">{label}</div><div className="break-all font-mono text-sm">{value || '—'}</div></div>{value && <button type="button" className="inline-flex shrink-0 items-center gap-1.5 self-start rounded-md border border-border px-2.5 py-1.5 text-xs hover:bg-muted sm:self-auto" onClick={() => copy(label, value)}>{copied === label ? <Check className="size-3.5" /> : <Clipboard className="size-3.5" />}{copied === label ? c.copied : c.copy}</button>}</div>)}</div><p className="text-sm text-muted-foreground">{c.browser}: {c.browserText}</p><div className="flex flex-wrap gap-2" role="tablist">{([['android', c.android], ['iphone', c.iphone], ['outlook', c.outlook]] as const).map(([id, label]) => <button key={id} type="button" role="tab" aria-selected={tab === id} className={`rounded-md px-3 py-2 text-sm ${tab === id ? 'bg-primary text-primary-foreground' : 'border border-border hover:bg-muted'}`} onClick={() => setTab(id)}>{label}</button>)}</div><ol className="grid gap-2 text-sm leading-relaxed">{steps.map((step, index) => <li key={step} className="flex gap-2"><span className="font-semibold text-primary">{index + 1}.</span><span>{step}</span></li>)}</ol><div className="rounded-lg border border-border bg-muted/30 p-4 text-sm leading-relaxed"><strong>{c.helpTitle}</strong><p className="mt-1 text-muted-foreground">{c.help}</p></div></div>}</section>
}
