export type MailSetupLang = 'tr' | 'en'

export const mailSetupCopy = {
  tr: {
    title: 'E-posta uygulamanıza ekleyin', intro: 'Telefonunuzda veya bilgisayarınızda kullanmak için aşağıdaki ayarları girin.', username: 'Kullanıcı adı', password: 'Şifre', passwordValue: 'Posta kutusu şifreniz', incoming: 'Gelen posta (IMAP)', outgoing: 'Giden posta (SMTP)', alternative: 'Alternatif: 587 / STARTTLS', webmail: 'Webmail', copy: 'Kopyala', copied: 'Kopyalandı', helpTitle: 'Giriş yapamıyorum', help: 'Kullanıcı adı tam e-posta adresiniz olmalıdır. Şifrenizi GLOVAL panelinizdeki Kurumsal E-posta sayfasından değiştirebilirsiniz. Yardım için destek talebi oluşturabilirsiniz.', android: 'Android (Gmail uygulaması)', androidSteps: ['Gmail’i açın, profil simgesine dokunun ve Başka bir hesap ekle → Diğer’i seçin.', 'E-posta adresinizi yazın, Kişisel (IMAP) seçeneğini seçin ve posta kutusu şifrenizi girin.', 'Gelen ve giden sunucu ayarlarını yukarıdaki tabloya göre girip kaydedin.'], iphone: 'iPhone / iPad (Mail)', iphoneSteps: ['Ayarlar → Mail → Hesaplar → Hesap Ekle → Diğer → Mail Hesabı Ekle yolunu izleyin.', 'Adınızı, e-posta adresinizi ve posta kutusu şifrenizi yazıp İleri’ye dokunun.', 'IMAP’i seçin, gelen ve giden sunucu ayarlarını girip Kaydet’e dokunun.'], outlook: 'Outlook (bilgisayar)', outlookSteps: ['Dosya → Hesap Ekle’ye gidin ve e-posta adresinizi yazın.', 'Gelişmiş seçenekler → Hesabımı el ile ayarlamama izin ver’i işaretleyip IMAP’i seçin.', 'Gelen ve giden sunucu ayarlarını girin, ardından posta kutusu şifrenizi yazın.'], browser: 'Tarayıcıdan (kurulum gerekmez)', browserText: 'Webmail adresine gidin; kullanıcı adı olarak tam e-posta adresinizi, şifre olarak posta kutusu şifrenizi kullanın.',
    greeting: 'Posta kutunuz kullanıma hazır. Webmail’den hemen giriş yapabilir veya aşağıdaki ayarlarla telefonunuza ve bilgisayarınıza ekleyebilirsiniz.', browserLead: 'Webmail adresine gidin:', browserRest: 'Kullanıcı adı olarak tam e-posta adresinizi, şifre olarak posta kutusu şifrenizi kullanın.', settingsTitle: 'Posta kutusu ayarları', incomingRow: 'Gelen posta (IMAP)', outgoingRow: 'Giden posta (SMTP)', alternativeRow: 'Alternatif giden port', alternativeValue: '587 / STARTTLS', appsTitle: 'Uygulamanıza ekleyin', passwordNote: 'Güvenliğiniz için şifreniz bu e-postada yer almaz.', subject: (address: string) => `${address} posta kutunuz hazır: telefonunuza ve bilgisayarınıza nasıl eklersiniz?`, resendSubject: (address: string) => `${address} posta kutusu kurulum bilgileri`
  },
  en: {
    title: 'Add it to your email app', intro: 'Use the settings below to use your mailbox on a phone or computer.', username: 'Username', password: 'Password', passwordValue: 'Your mailbox password', incoming: 'Incoming mail (IMAP)', outgoing: 'Outgoing mail (SMTP)', alternative: 'Alternative: 587 / STARTTLS', webmail: 'Webmail', copy: 'Copy', copied: 'Copied', helpTitle: 'Cannot sign in?', help: 'Your username must be your full email address. You can change your password from the Business Email page in your GLOVAL dashboard. You can also open a support ticket.', android: 'Android (Gmail app)', androidSteps: ['Open Gmail, tap your profile icon, then choose Add another account → Other.', 'Enter your address, choose Personal (IMAP), and enter your mailbox password.', 'Enter the incoming and outgoing server settings from the table above, then save.'], iphone: 'iPhone / iPad (Mail)', iphoneSteps: ['Go to Settings → Mail → Accounts → Add Account → Other → Add Mail Account.', 'Enter your name, address, and mailbox password, then tap Next.', 'Choose IMAP, enter the incoming and outgoing server settings, then tap Save.'], outlook: 'Outlook (desktop)', outlookSteps: ['Go to File → Add Account, then enter your address.', 'Choose Advanced options → Let me set up my account manually, then pick IMAP.', 'Enter the incoming and outgoing server settings, then your mailbox password.'], browser: 'In your browser (no setup)', browserText: 'Go to webmail and use your full address and mailbox password.',
    greeting: 'Your mailbox is ready to use. Sign in to webmail right away, or add it to your phone and computer with the settings below.', browserLead: 'Go to webmail:', browserRest: 'Use your full address as the username and your mailbox password as the password.', settingsTitle: 'Mailbox settings', incomingRow: 'Incoming mail (IMAP)', outgoingRow: 'Outgoing mail (SMTP)', alternativeRow: 'Alternative outgoing port', alternativeValue: '587 / STARTTLS', appsTitle: 'Add it to your app', passwordNote: 'For your security, your password is not included in this email.', subject: (address: string) => `Your mailbox ${address} is ready: how to add it to your phone and computer`, resendSubject: (address: string) => `Setup instructions for ${address}`
  }
} as const

export function getMailSetupCopy(lang: string) { return mailSetupCopy[lang === 'tr' ? 'tr' : 'en'] }
