import type { BillingProfileCopyLanguage, BillingProfileExportFilter } from '@/lib/billing-profile-types'

const billingProfileCopy = {
  tr: {
    title: 'Fatura bilgileri',
    subtitle: 'Faturalarınızın doğru bilgilerle düzenlenmesi için bu profili tamamlayın.',
    typeLabel: 'Fatura türü',
    individual: 'Bireysel',
    company: 'Kurumsal',
    fullName: 'Ad soyad',
    fullNameOptional: 'Yetkili kişi (isteğe bağlı)',
    companyTitle: 'Firma unvanı',
    taxOffice: 'Vergi dairesi',
    nationalId: 'T.C. kimlik numarası',
    taxNumber: 'Vergi kimlik numarası (VKN)',
    addressLine: 'Açık adres',
    district: 'İlçe',
    city: 'İl',
    postalCode: 'Posta kodu (isteğe bağlı)',
    country: 'Ülke',
    phone: 'Telefon',
    companyHint: "Bu bir şirket unvanına benziyor. Kurumsal fatura için 'Kurumsal'ı seçin.",
    switchToCompany: 'Kurumsal faturaya geç',
    eInvoiceHint: 'Şirketiniz e-Fatura sistemine kayıtlıysa işaretleyin.',
    invoiceEmail: 'Fatura e-posta adresi',
    eInvoicePayer: 'E-Fatura mükellefiyim',
    tcknHint: '11 haneli T.C. kimlik numaranızı girin.',
    vknHint: '10 haneli vergi kimlik numaranızı girin.',
    identifierSaved: 'Kayıtlı numara',
    identifierUnchanged: 'Değiştirmek için yeni numarayı girin. Boş bırakırsanız kayıtlı numara korunur.',
    countryHint: 'ISO 3166-1 alpha-2 ülke kodu; Türkiye için TR.',
    save: 'Bilgileri kaydet',
    saving: 'Kaydediliyor…',
    edit: 'Düzenle',
    cancel: 'Vazgeç',
    saved: 'Fatura bilgileriniz kaydedildi.',
    complete: 'Bilgiler tamamlandı',
    incomplete: 'Bilgiler eksik',
    notProvided: 'Henüz fatura bilgisi eklenmedi.',
    unavailable: 'Fatura bilgileri şu anda kullanılamıyor. Lütfen daha sonra tekrar deneyin.',
    saveFailed: 'Bilgiler kaydedilemedi. Lütfen tekrar deneyin.',
    loadFailed: 'Fatura bilgileri yüklenemedi.',
    validation: {
      required: 'Bu alanı doldurun.',
      invalid: 'Geçerli bir bilgi girin.',
      too_long: 'Bu alan izin verilen uzunluğu aşıyor.',
    },
    bannerTitle: 'Fatura bilgileriniz eksik',
    bannerBody: 'Faturanızın düzenlenebilmesi için fatura bilgilerinizi girin.',
    bannerCta: 'Fatura bilgilerini gir',
    accountLink: 'Fatura bilgileri',
    notificationReminder: '\n\nFaturanızı düzenleyebilmemiz için profilinizden fatura bilgilerinizi girin: https://gloval.ai/billing#fatura-bilgileri',
    creditReminder: 'Faturanızı düzenleyebilmemiz için profilinizden fatura bilgilerinizi girin.',
    yes: 'Evet',
    no: 'Hayır',
    adminNav: 'Fatura profilleri',
    adminTitle: 'Fatura profilleri',
    adminSubtitle: 'Ücretli abonelerin fatura bilgilerini görüntüleyin ve eksik kayıtları dışa aktarın.',
    adminUnavailable: 'Fatura profili tablosu kullanılamıyor. Önce 028 numaralı SQL dosyasını ayrıca uygulayın.',
    adminSearch: 'E-posta, ad veya firma ara',
    filterAll: 'Tüm profiller',
    filterIncomplete: 'Eksik profiller',
    filterComplete: 'Tam profiller',
    exportAll: 'CSV dışa aktar',
    exportIncomplete: 'Eksikleri CSV olarak indir',
    exportComplete: 'Tam profilleri CSV olarak indir',
    exporting: 'Dışa aktarılıyor…',
    exportFailed: 'Dışa aktarma başarısız oldu. Lütfen tekrar deneyin.',
    exportAuditFailed: 'Dışa aktarma kaydedilemedi; dosya oluşturulmadı.',
    exportDone: 'CSV dosyası indirildi.',
    noRows: 'Bu filtrede kayıt yok.',
    emailColumn: 'Hesap e-postası',
    customerColumn: 'Müşteri türü',
    taxOfficeColumn: 'Vergi dairesi',
    identifierColumn: 'Kimlik / vergi no.',
    statusColumn: 'Durum',
    actionColumn: 'İşlem',
    details: 'Görüntüle',
    hideDetails: 'Gizle',
    user: 'Kullanıcı',
    plan: 'Paket',
    subscriptionStatus: 'Abonelik',
    profileDetails: 'Fatura profili',
    address: 'Adres',
    invoiceEmailColumn: 'Fatura e-postası',
    phoneColumn: 'Telefon',
    companyColumn: 'Firma unvanı',
    fullNameColumn: 'Ad soyad / yetkili',
    updatedAt: 'Son güncelleme',
    missingProfile: 'Profil eklenmemiş',
    tcknLabel: 'T.C. kimlik no.',
    vknLabel: 'VKN',
    csvHeaders: [
      'Kullanıcı ID',
      'Hesap e-postası',
      'Paket',
      'Abonelik durumu',
      'Müşteri türü',
      'Ad soyad / yetkili',
      'Firma unvanı',
      'Vergi dairesi',
      'T.C. kimlik numarası',
      'Vergi kimlik numarası',
      'Fatura e-posta adresi',
      'Açık adres',
      'İlçe',
      'İl',
      'Posta kodu',
      'Ülke kodu',
      'Telefon',
      'E-Fatura mükellefi',
      'Profil tamamlandı',
      'Güncellendi',
    ],
  },
  en: {
    title: 'Billing details',
    subtitle: 'Complete this profile so invoices use the correct details.',
    typeLabel: 'Customer type',
    individual: 'Individual',
    company: 'Company',
    fullName: 'Full name',
    fullNameOptional: 'Contact person (optional)',
    companyTitle: 'Registered company name',
    taxOffice: 'Tax office',
    nationalId: 'Turkish national ID number',
    taxNumber: 'Tax identification number (VKN)',
    addressLine: 'Street address',
    district: 'District',
    city: 'City',
    postalCode: 'Postal code (optional)',
    country: 'Country',
    phone: 'Phone',
    companyHint: 'This looks like a company name. Choose “Company” for a company invoice.',
    switchToCompany: 'Switch to company invoice',
    eInvoiceHint: 'Check this if your company is registered for the e-Invoice system.',
    invoiceEmail: 'Invoice email',
    eInvoicePayer: 'I am registered for e-Invoice',
    tcknHint: 'Enter your 11-digit Turkish national ID number.',
    vknHint: 'Enter your 10-digit Turkish tax ID number.',
    identifierSaved: 'Number on file',
    identifierUnchanged: 'Enter a new number to replace it. Leave blank to keep the saved number.',
    countryHint: 'ISO 3166-1 alpha-2 country code; use TR for Türkiye.',
    save: 'Save billing details',
    saving: 'Saving…',
    edit: 'Edit',
    cancel: 'Cancel',
    saved: 'Your billing details were saved.',
    complete: 'Complete',
    incomplete: 'Incomplete',
    notProvided: 'No billing details have been added yet.',
    unavailable: 'Billing details are unavailable right now. Please try again later.',
    saveFailed: 'We could not save your details. Please try again.',
    loadFailed: 'We could not load billing details.',
    validation: {
      required: 'This field is required.',
      invalid: 'Enter a valid value.',
      too_long: 'This value exceeds the allowed length.',
    },
    bannerTitle: 'Your billing details are incomplete',
    bannerBody: 'Enter your billing details so we can issue your invoice.',
    bannerCta: 'Enter billing details',
    accountLink: 'Billing details',
    notificationReminder: '\n\nEnter your billing details in your profile so we can issue your invoice: https://gloval.ai/billing#fatura-bilgileri',
    creditReminder: 'Enter your billing details in your profile so we can issue your invoice.',
    yes: 'Yes',
    no: 'No',
    adminNav: 'Billing profiles',
    adminTitle: 'Billing profiles',
    adminSubtitle: 'Review paid subscribers’ invoice details and export incomplete profiles.',
    adminUnavailable: 'The billing profile table is unavailable. Apply SQL file 028 separately first.',
    adminSearch: 'Search email, name or company',
    filterAll: 'All profiles',
    filterIncomplete: 'Incomplete profiles',
    filterComplete: 'Complete profiles',
    exportAll: 'Export CSV',
    exportIncomplete: 'Download incomplete CSV',
    exportComplete: 'Download complete CSV',
    exporting: 'Exporting…',
    exportFailed: 'Export failed. Please try again.',
    exportAuditFailed: 'The export could not be logged, so no file was created.',
    exportDone: 'CSV downloaded.',
    noRows: 'No records match this filter.',
    emailColumn: 'Account email',
    customerColumn: 'Customer type',
    taxOfficeColumn: 'Tax office',
    identifierColumn: 'ID / tax no.',
    statusColumn: 'Status',
    actionColumn: 'Action',
    details: 'View',
    hideDetails: 'Hide',
    user: 'User',
    plan: 'Plan',
    subscriptionStatus: 'Subscription',
    profileDetails: 'Billing profile',
    address: 'Address',
    invoiceEmailColumn: 'Invoice email',
    phoneColumn: 'Phone',
    companyColumn: 'Company name',
    fullNameColumn: 'Name / contact',
    updatedAt: 'Last updated',
    missingProfile: 'No profile',
    tcknLabel: 'National ID',
    vknLabel: 'VKN',
    csvHeaders: [
      'User ID',
      'Account email',
      'Plan',
      'Subscription status',
      'Customer type',
      'Full name / contact',
      'Registered company name',
      'Tax office',
      'Turkish national ID',
      'Tax identification number',
      'Invoice email',
      'Street address',
      'District',
      'City',
      'Postal code',
      'Country code',
      'Phone',
      'e-Invoice registered',
      'Profile complete',
      'Updated at',
    ],
  },
} as const

export type BillingProfileCopy = (typeof billingProfileCopy)[BillingProfileCopyLanguage]

export function getBillingProfileCopy(language: string): BillingProfileCopy {
  return billingProfileCopy[language === 'tr' ? 'tr' : 'en']
}

export function billingProfileReminderText(language: BillingProfileCopyLanguage = 'tr'): string {
  return billingProfileCopy[language].notificationReminder
}

export function appendBillingProfileReminder(
  body: string,
  incomplete: boolean,
  language: BillingProfileCopyLanguage = 'tr',
): string {
  return incomplete ? `${body}${billingProfileReminderText(language)}` : body
}

export function billingProfileCreditReminder(language: string): string {
  return getBillingProfileCopy(language).creditReminder
}

export function isBillingProfileExportFilter(value: unknown): value is BillingProfileExportFilter {
  return value === 'all' || value === 'incomplete' || value === 'complete'
}
