import type { Lang } from '@/lib/i18n'

/** Copy for the admin "Ödeme bekleyenler" screen (Turkish + English; other locales fall back to English). */

const tr = {
  nav: 'Ödeme bekleyenler',
  title: 'Ödeme bekleyenler',
  subtitle: 'Ödemesi gecikmiş abonelikler. Kullanıcıyla iletişime geç, ödemeyi kaydet veya hediye süre tanımla.',
  searchPlaceholder: 'E-posta veya ad ara',
  filterAllReasons: 'Tüm durumlar',
  filterAllPlans: 'Tüm paketler',
  filterNoContact: 'İletişim kurulmadı',
  empty: 'Ödeme bekleyen abonelik yok.',
  reason: { past_due: 'Ödeme gecikti', payment_failed_suspended: 'Askıda (ödenmedi)', period_expired: 'Dönem bitti, yenilenmedi' },
  colUser: 'Kullanıcı',
  colPlan: 'Paket',
  colStatus: 'Durum',
  colOverdue: 'Gecikme',
  colGrace: 'Grace bitişi',
  colServices: 'Site / Mail',
  colActions: 'İşlemler',
  days: '{n} gün',
  today: 'Bugün',
  noDate: '—',
  sites: 'Site',
  mail: 'Mail',
  siteState: { active: 'açık', suspended: 'askıda', none: 'yok' },
  mailState: { active: 'aktif', grace: 'grace', suspended: 'askıda', none: 'yok' },
  providerManaged: 'Sağlayıcı yönetimli',
  call: 'Ara',
  whatsapp: 'WhatsApp',
  note: 'Not ekle',
  markPaid: 'Ödendi olarak işaretle',
  gift: 'Hediye süre',
  history: 'Geçmiş',
  noHistory: 'Kayıt yok.',
  lastContact: 'Son iletişim',
  never: 'Hiç iletişim kurulmadı',
  prev: 'Önceki',
  next: 'Sonraki',
  pageOf: 'Sayfa {page} / {count} · {total} kayıt',
  outcomeLabel: 'Sonuç',
  outcome: { contacted: 'Ulaşıldı', unreachable: 'Ulaşılamadı', promised: 'Ödeme sözü verdi' },
  promisedFor: 'Söz verilen tarih',
  noteLabel: 'Not',
  reasonLabel: 'Neden (denetim kaydına yazılır)',
  save: 'Kaydet',
  cancel: 'Vazgeç',
  working: 'İşleniyor…',
  paidTitle: 'Ödemeyi kaydet',
  paidBody: 'Havale/EFT/nakit ile alınan ödeme için {plan} aboneliği aktif edilir ve yeni dönem başlar. Askıdaki siteler açılır, mail erişimi senkronize edilir.',
  paidAmount: 'Kayıt edilecek tutar: {amount}',
  giftTitle: 'Hediye süre tanımla',
  giftBody: 'Ücretsiz süre eklenir; abonelik aktif edilir. Tutar 0 olarak kaydedilir.',
  giftMonths: 'Süre',
  giftMonthsOption: '{n} ay',
  providerWarning: 'Bu abonelik ödeme sağlayıcısı üzerinden yönetiliyor ({provider}). Sağlayıcıda ayrıca bir tahsilat olursa süre üst üste eklenir; sağlayıcı tarafına hiçbir istek gönderilmez.',
  success: 'İşlem tamamlandı.',
  auditWarning: 'İşlem tamamlandı ancak denetim kaydı yazılamadı.',
  confirmPaid: 'Ödemeyi kaydet ve aboneliği aktif et',
  confirmGift: 'Hediye süreyi tanımla',
  errors: {
    reason_required: 'Neden en az 3 karakter olmalı.',
    reason_too_long: 'Neden çok uzun.',
    invalid_months: 'Geçersiz süre.',
    free_plan_no_payment: 'Ücretsiz pakete ödeme kaydedilemez.',
    subscription_not_settleable: 'Bu abonelik durumunda işlem yapılamaz.',
    subscription_not_found: 'Abonelik bulunamadı.',
    plan_not_found: 'Paket bulunamadı.',
    audit_unavailable: 'Denetim tablosu hazır değil (024 betiği uygulanmamış). İşlem yapılmadı.',
    duplicate_recent: 'Bu abonelikte az önce işlem yapıldı. Lütfen bekleyip tekrar kontrol et.',
    settlement_failed: 'İşlem tamamlanamadı.',
    note_required: 'Not boş olamaz.',
    note_too_long: 'Not çok uzun.',
    invalid_date: 'Geçersiz tarih.',
    insert_failed: 'Kaydedilemedi.',
    generic: 'Bir şeyler ters gitti.',
  } as Record<string, string>,
}

export type OverdueCopy = typeof tr

const en: OverdueCopy = {
  nav: 'Unpaid',
  title: 'Unpaid subscriptions',
  subtitle: 'Subscriptions with overdue payments. Contact the user, record a payment or grant free time.',
  searchPlaceholder: 'Search email or name',
  filterAllReasons: 'All statuses',
  filterAllPlans: 'All plans',
  filterNoContact: 'Not contacted',
  empty: 'No unpaid subscriptions.',
  reason: { past_due: 'Payment overdue', payment_failed_suspended: 'Suspended (unpaid)', period_expired: 'Period ended, not renewed' },
  colUser: 'User',
  colPlan: 'Plan',
  colStatus: 'Status',
  colOverdue: 'Overdue',
  colGrace: 'Grace ends',
  colServices: 'Site / Mail',
  colActions: 'Actions',
  days: '{n} days',
  today: 'Today',
  noDate: '—',
  sites: 'Sites',
  mail: 'Mail',
  siteState: { active: 'live', suspended: 'suspended', none: 'none' },
  mailState: { active: 'active', grace: 'grace', suspended: 'suspended', none: 'none' },
  providerManaged: 'Provider-managed',
  call: 'Call',
  whatsapp: 'WhatsApp',
  note: 'Add note',
  markPaid: 'Mark as paid',
  gift: 'Gift time',
  history: 'History',
  noHistory: 'No entries.',
  lastContact: 'Last contact',
  never: 'Never contacted',
  prev: 'Previous',
  next: 'Next',
  pageOf: 'Page {page} / {count} · {total} records',
  outcomeLabel: 'Outcome',
  outcome: { contacted: 'Reached', unreachable: 'Unreachable', promised: 'Promised payment' },
  promisedFor: 'Promised date',
  noteLabel: 'Note',
  reasonLabel: 'Reason (stored in the audit log)',
  save: 'Save',
  cancel: 'Cancel',
  working: 'Working…',
  paidTitle: 'Record payment',
  paidBody: 'For a payment received by bank transfer/cash, the {plan} subscription is activated and a new period starts. Suspended sites are restored and mail access is synced.',
  paidAmount: 'Amount to record: {amount}',
  giftTitle: 'Grant free time',
  giftBody: 'Free time is added and the subscription is activated. The amount is recorded as 0.',
  giftMonths: 'Duration',
  giftMonthsOption: '{n} mo',
  providerWarning: 'This subscription is managed by a payment provider ({provider}). If the provider also collects a payment, the time stacks; no request is sent to the provider.',
  success: 'Done.',
  auditWarning: 'Done, but the audit entry could not be written.',
  confirmPaid: 'Record payment and activate',
  confirmGift: 'Grant free time',
  errors: {
    reason_required: 'Reason must be at least 3 characters.',
    reason_too_long: 'Reason is too long.',
    invalid_months: 'Invalid duration.',
    free_plan_no_payment: 'A payment cannot be recorded on a free plan.',
    subscription_not_settleable: 'This subscription status cannot be settled.',
    subscription_not_found: 'Subscription not found.',
    plan_not_found: 'Plan not found.',
    audit_unavailable: 'The audit table is not ready (script 024 not applied). Nothing was changed.',
    duplicate_recent: 'An action was just recorded on this subscription. Please wait and check again.',
    settlement_failed: 'The action could not be completed.',
    note_required: 'Note cannot be empty.',
    note_too_long: 'Note is too long.',
    invalid_date: 'Invalid date.',
    insert_failed: 'Could not save.',
    generic: 'Something went wrong.',
  },
}

export function overdueT(lang: Lang): OverdueCopy {
  return lang === 'tr' ? tr : en
}

export function fillCopy(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? ''))
}
